spring:
  application:
    name: CloudStorage

  datasource:
    url: jdbc:postgresql://localhost:5432/cloudstorage?currentSchema=cloudstorage
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never
      continue-on-error: false
      data-locations: classpath:init-data.sql
      schema-locations: classpath:init-schema.sql

  data:
    jdbc:
      dialect: postgresql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

token:
  signing:
    key: token
