spring:
  application:
    name: CloudStorage

  datasource:
    url: jdbc:postgresql://localhost:5432/cloudstorage?currentSchema=cloudstorage
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public

  data:
    jdbc:
      dialect: postgresql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true



token:
  signing:
    key: token
    access_token: 36000000 # 10 hours
    refresh_token: 252000000 # 7 days
