package org.y9nba.app.constant;

public enum Action {
    ACTION_CREATE,
    ACTION_RENAME,
    ACTION_UPDATE,
    ACTION_MOVE,
    ACTION_COPY,
    ACTION_DOWNLOAD,
    ACTION_ADD_ACCESS,
    ACTION_DEL_ACCESS,
    ACTION_MAKE_PUBLIC,
    ACTION_MAKE_PRIVATE
}
